# Generated by Django 4.2.3 on 2023-07-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("adult", models.BooleanField()),
                ("backdrop_path", models.CharField(max_length=255)),
                ("genre_ids", models.JSONField()),
                ("movie_id", models.CharField(max_length=255, unique=True)),
                ("original_language", models.CharField(max_length=255)),
                ("original_title", models.CharField(max_length=255)),
                ("overview", models.TextField()),
                ("popularity", models.DecimalField(decimal_places=2, max_digits=6)),
                ("poster_path", models.CharField(max_length=255)),
                ("release_date", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("video", models.BooleanField()),
                ("vote_average", models.DecimalField(decimal_places=2, max_digits=6)),
                ("vote_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Movie",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("author", models.CharField(max_length=255)),
                ("author_details", models.JSONField()),
                ("content", models.TextField()),
                ("review_created_at", models.DateTimeField()),
                ("review_id", models.CharField(max_length=255)),
                ("review_updated_at", models.DateTimeField()),
                ("url", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
            options={
                "db_table": "Review",
            },
        ),
    ]
