# Generated by Django 4.2.3 on 2023-07-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="overview",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="popularity",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_average",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_count",
            field=models.IntegerField(null=True),
        ),
    ]
