# Generated by Django 4.2.3 on 2023-07-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_movie_overview_alter_movie_popularity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="url",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
